files:
  - source: data/menus/main_menu.xml
    translation: /Integration/%two_letters_code%/%original_file_name%
  - source: /po/en.po
    translation: /po/A-35/%three_letters_code%/%original_file_name%
